In [2]:
import tensorflow as tf

## 플레이스홀더란

In [3]:
help(tf.placeholder)

Help on function placeholder in module tensorflow.python.ops.array_ops:

placeholder(dtype, shape=None, name=None)
    Inserts a placeholder for a tensor that will be always fed.
    
    **Important**: This tensor will produce an error if evaluated. Its value must
    be fed using the `feed_dict` optional argument to `Session.run()`,
    `Tensor.eval()`, or `Operation.run()`.
    
    For example:
    
    ```python
    x = tf.placeholder(tf.float32, shape=(1024, 1024))
    y = tf.matmul(x, x)
    
    with tf.Session() as sess:
      print(sess.run(y))  # ERROR: will fail because x was not fed.
    
      rand_array = np.random.rand(1024, 1024)
      print(sess.run(y, feed_dict={x: rand_array}))  # Will succeed.
    ```
    
    Args:
      dtype: The type of elements in the tensor to be fed.
      shape: The shape of the tensor to be fed (optional). If the shape is not
        specified, you can feed a tensor of any shape.
      name: A name for the operation (optional).
    
    Re

### 하나의 플레이스 홀더를 지정하기 : dtype, shape, name

In [9]:
X = tf.placeholder(tf.float32,[None,3])

In [10]:
X

<tf.Tensor 'Placeholder_1:0' shape=(?, 3) dtype=float32>

In [11]:
Y = tf.placeholder(tf.float32,[None,None,3])

In [12]:
Y

<tf.Tensor 'Placeholder_2:0' shape=(?, ?, 3) dtype=float32>

## Shape에 왜 None을 지정하는지? 실제 최종 원소의 갯수는 알지만 차원의 임의적으로 처리할 경우 사용

## [None,3] 의 의미는 ?

    shape를 표시하고 앞에 차원과 상관없이 실제 뒤에 원소가 3개를 말한다.
    

In [5]:
x_data = [[1,2,3],[4,5,6]]

In [6]:
y_data = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]

## feed_dict 에서 실제 딕셔너리로 플레이스 홀더의 데이터를 받도록 처리한다.



In [13]:
sess = tf.Session()

In [14]:
print(sess.run(X,feed_dict={X:x_data}))

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [15]:
print(sess.run(Y,feed_dict={Y:y_data}))

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]]]
