In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.1.0-dev20191015'

In [3]:
tf.Tensor

tensorflow.python.framework.ops.Tensor

In [4]:
dir(tf.Tensor)

['OVERLOADABLE_OPERATORS',
 '_USE_EQUALITY',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__copy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_as_node_def_input',
 '_as_tf_output',
 '_c_api_shape',
 '_create_with_tf_output',
 '_disallow_bool_ca

In [5]:
dir(tf.constant)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_tf_api_names',
 '_tf_api_names_v1']

## 상수도 실제 생성되면 tensor로 만들어진다.

In [6]:
tf.constant(100)

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [7]:
help(tf.constant)

Help on function constant in module tensorflow.python.framework.constant_op:

constant(value, dtype=None, shape=None, name='Const')
    Creates a constant tensor from a tensor-like object.
    
    Note: All eager `tf.Tensor` values are immutable (in contrast to
    `tf.Variable`). There is nothing especially _constant_ about the value
    returned from `tf.constant`. This function it is not fundamentally different
    from `tf.convert_to_tensor`. The name `tf.constant` comes from the symbolic
    APIs (like `tf.data` or keras functional models) where the `value` is embeded
    in a `Const` node in the `tf.Graph`. `tf.constant` is useful for asserting
    that the value can be embedded that way.
    
    If the argument `dtype` is not specified, then the type is inferred from
    the type of `value`.
    
    >>> # Constant 1-D Tensor from a python list.
    >>> tf.constant([1, 2, 3, 4, 5, 6])
    <tf.Tensor: shape=(6,), dtype=int32,
        numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)

## 변수 클래스 알아보기

In [8]:
dir(tf.Variable)

['SaveSliceInfo',
 '_OverloadAllOperators',
 '_OverloadOperator',
 '_TensorConversionFunction',
 '__abs__',
 '__add__',
 '__and__',
 '__array_priority__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__iter__',
 '__le__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_add_variable_with_custom_getter',
 '_checkpoint_dependencies',
 '_deferred_dependencies',
 '_gather_saveables_for_chec

In [9]:
help(tf.Variable)

Help on class Variable in module tensorflow.python.ops.variables:

class Variable(tensorflow.python.training.tracking.base.Trackable)
 |  Variable(*args, **kwargs)
 |  
 |  See the [variable guide](https://tensorflow.org/guide/variable).
 |  
 |  A variable maintains shared, persistent state manipulated by a program.
 |  
 |  The `Variable()` constructor requires an initial value for the variable, which
 |  can be a `Tensor` of any type and shape. This initial value defines the type
 |  and shape of the variable. After construction, the type and shape of the
 |  variable are fixed. The value can be changed using one of the assign methods.
 |  
 |  >>> v = tf.Variable(1.)
 |  >>> v.assign(2.)
 |  <tf.Variable ... shape=() dtype=float32, numpy=2.0>
 |  >>> v.assign_add(0.5)
 |  <tf.Variable ... shape=() dtype=float32, numpy=2.5>
 |  
 |  The `shape` argument to `Variable`'s constructor allows you to construct a
 |  variable with a less defined shape than its `initial_value`:
 |  
 |  >>>

### 변수를 생성하면 하나의 변수 객체가 만들어진다.

In [10]:
a = tf.Variable(0,name="a")

In [11]:
a

<tf.Variable 'a:0' shape=() dtype=int32, numpy=0>

### 변수값을 assign 메소드로 변경이 가능하다.

In [12]:
a.assign(a+1)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=1>

### 변수의 값을 보면 실제 tensor로 보인다.

In [13]:
a.value()

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [14]:
a.read_value()

<tf.Tensor: shape=(), dtype=int32, numpy=1>