In [2]:
import tensorflow as tf

In [3]:
import numpy as np

In [4]:
a = tf.constant(np.array([1,2,3]))

## 대화형으로 텐서플로우를 실행하기

In [6]:
tf.InteractiveSession()

## 함수를 eval 메소드로 실행하기

In [7]:
tf.shape(a).eval()

array([3], dtype=int32)

In [8]:
b = tf.stack([a,a,a],axis=0)

In [9]:
tf.shape(b).eval()

array([3, 3], dtype=int32)

In [10]:
b

<tf.Tensor 'stack:0' shape=(3, 3) dtype=int64>

## 텐서 내부도 eval 메소드로 실행해서 실제 값을 확인하기

In [11]:
b.eval()

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## 평균을 축에 따라 계산하기

In [12]:
tf.reduce_mean(b)

<tf.Tensor 'Mean:0' shape=() dtype=int64>

In [13]:
tf.reduce_mean(b).eval()

2

In [14]:
tf.reduce_mean(b, axis=1).eval()

array([2, 2, 2])

In [15]:
tf.reduce_mean(b, axis=0).eval()

array([1, 2, 3])

## one_hot 처리

In [20]:
c = tf.one_hot([1,2,3],depth=4)

In [21]:
c.eval()

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]], dtype=float32)