In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.1.0-dev20191015'

In [3]:
import numpy as np

# tf.placeholder삭제 됨 :   X = tf.placeholder(tf.float32, [None,3])

In [6]:
x_data = np.array([[1,2,3],[4,5,6]])

In [7]:
X = x_data

## 정규 분포를 기준으로 변수 할당하기

In [8]:
W = tf.Variable(tf.random.normal([3,2]))

In [9]:
W

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[-0.87410426,  1.5577521 ],
       [ 0.41273925, -1.2222991 ],
       [-0.49574536,  0.9910723 ]], dtype=float32)>

In [13]:
b = tf.Variable(tf.random.normal([2,1]))

In [14]:
b

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[0.0719943],
       [1.1391168]], dtype=float32)>

In [21]:
c = tf.Variable(np.random.normal(0,1,size=(2,1)))

In [22]:
c

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
array([[0.01140967],
       [1.60765063]])>

## 실제 두개의 변수를 계산한다.

In [23]:
X.shape

(2, 3)

In [24]:
W.shape

TensorShape([3, 2])

In [25]:
x_data.shape

(2, 3)

## 텐서플로우 matmul은 넘파이와 텐서플로우 게산시 에외 발생

In [30]:
try :
    tf.matmul(X,W.numpy()) + b
except Exception as e:
    print(e)

cannot compute MatMul as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:MatMul] name: MatMul/


In [33]:
X.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
W.dtype

tf.float32

In [32]:
try :
    tf.matmul(X.astype('float64'),W.numpy()) + b
except Exception as e:
    print(e)

cannot compute MatMul as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:MatMul] name: MatMul/


## tf.matmul일때는 두 개가 텐서일때 계산

In [44]:
tf.constant(X, dtype=tf.float32)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [47]:
tf.matmul(tf.constant(X, dtype=tf.float32),W) + b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.4638674,  2.1583652],
       [-3.2680764,  7.205064 ]], dtype=float32)>

In [28]:
expr = np.matmul(X,W.numpy()) + b

In [29]:
expr

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.4638675,  2.1583652],
       [-3.2680764,  7.2050633]], dtype=float32)>