In [2]:
import tensorflow as tf

In [20]:
import numpy as np

In [7]:
X = tf.placeholder(tf.float32, [None,3])

In [21]:
x_data = np.array([[1,2,3],[4,5,6]])

## 정규 분포를 기준으로 변수 할당하기

In [3]:
W = tf.Variable(tf.random_normal([3,2]))

In [4]:
W

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32_ref>

In [5]:
b = tf.Variable(tf.random_normal([2,1]))

In [6]:
b

<tf.Variable 'Variable_1:0' shape=(2, 1) dtype=float32_ref>

## 실제 두개의 변수를 계산한다.

In [16]:
X.shape

TensorShape([Dimension(None), Dimension(3)])

In [17]:
W.shape

TensorShape([Dimension(3), Dimension(2)])

In [22]:
x_data.shape

(2, 3)

In [8]:
expr = tf.matmul(X,W) + b

In [9]:
sess = tf.Session()

In [10]:
sess.run(tf.global_variables_initializer())

In [11]:
sess.run(W)

array([[-0.44088566,  0.36643481],
       [-1.36134601,  0.97977185],
       [ 0.44495541, -1.12695134]], dtype=float32)

In [12]:
sess.run(b)

array([[-0.04371812],
       [-0.45596349]], dtype=float32)

## 2행 3열과 3행 2열의 두 행렬에 대해 행렬연산을 처리하므로 2행 2열의 행렬이 만들어진 것을 알 수 있다

In [14]:
sess.run(expr, feed_dict={X:x_data})

array([[-1.87242937, -1.09859371],
       [-6.35650349, -0.85307348]], dtype=float32)

In [15]:
sess.close()