In [1]:
import tensorflow as tf

C:\Users\06411\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.__version__

'1.9.0'

### 그래프 그리기

In [3]:
a = tf.placeholder(tf.float32)

In [4]:
b = tf.placeholder(tf.float32)

In [5]:
c = tf.multiply(a,b)

In [6]:
print('c = ', c)

c =  Tensor("Mul:0", dtype=float32)


### 실행하기

In [7]:
sess = tf.Session()

In [8]:
print(" sess run =", sess.run(c, feed_dict={a:3.,b:4.}))

 sess run = 12.0


## Placeholder에 텐서 넣기

In [10]:
x = tf.placeholder(tf.float32, shape=(1024,1024))

In [11]:
y = tf.matmul(x,x)

In [12]:
sess = tf.Session()

#### 넘파이를 통해 배열처리

In [13]:
import numpy as np

In [14]:
rand_array = np.random.rand(1024,1024)

In [15]:
print("sess run", sess.run(y, feed_dict={x: rand_array}))

sess run [[261.5743  259.7892  262.5343  ... 261.4117  250.35818 256.73407]
 [257.21262 248.18169 258.03085 ... 255.98204 243.51447 247.72093]
 [252.53368 247.85655 255.7054  ... 255.15399 244.85587 244.56494]
 ...
 [253.21707 245.7144  244.37987 ... 249.29674 237.27835 243.02055]
 [247.46684 246.87642 251.93129 ... 255.60793 244.66858 248.8231 ]
 [257.37674 252.30893 258.56012 ... 257.79013 248.7173  252.94621]]
