In [2]:
import tensorflow as tf

In [3]:
import numpy as np

In [4]:
a = tf.constant(np.array([1,2,3]))

## 대화형으로 텐서플로우를 실행하기

In [5]:
tf.InteractiveSession()

## 평균을 축에 따라 계산하기

In [6]:
tf.reduce_mean(a)

<tf.Tensor 'Mean:0' shape=() dtype=int64>

In [7]:
tf.reduce_mean(a).eval()

2

## 1차원을 2차원으로 변형해서 새로운 텐서를 생성

In [8]:
b = tf.stack([a,a,a],axis=1)

In [11]:
b.eval()

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

### 1번 축에 대한 평균

In [9]:
tf.reduce_mean(b, axis=1).eval()

array([1, 2, 3])

### 0번 축에 대한 평균

In [10]:
tf.reduce_mean(b, axis=0).eval()

array([2, 2, 2])

### 전체에 대한 평균

In [12]:
tf.reduce_mean(b).eval()

2

## 합산하기 

In [13]:
tf.reduce_sum(b)

<tf.Tensor 'Sum:0' shape=() dtype=int64>

In [14]:
tf.reduce_sum(b).eval()

18

In [15]:
tf.reduce_sum(b,axis=0).eval()

array([6, 6, 6])

In [16]:
tf.reduce_sum(b,axis=1).eval()

array([3, 6, 9])

## 전체를 곱하기

In [17]:
tf.reduce_prod(b).eval()

216

## 최대값과 최소값

In [18]:
tf.reduce_min(b).eval()

1

In [19]:
tf.reduce_max(b).eval()

3