In [2]:
import tensorflow as tf

In [9]:
!conda list

# packages in environment at C:\Program Files\Anaconda3:
#
_license                  1.1                      py35_1  
_nb_ext_conf              0.3.0                    py35_0  
alabaster                 0.7.9                    py35_0  
anaconda                  4.2.0               np111py35_0  
anaconda-clean            1.0.0                    py35_0  
anaconda-client           1.5.1                    py35_0  
anaconda-navigator        1.3.1                    py35_0  
argcomplete               1.0.0                    py35_1  
astroid                   1.4.7                    py35_0  
astropy                   1.2.1               np111py35_0  
babel                     2.3.4                    py35_0  
backports                 1.0                      py35_0  
beautifulsoup4            4.5.1                    py35_0  
bitarray                  0.8.1                    py35_1  
blaze                     0.10.1                   py35_0  
bokeh                     0.12.2         

In [3]:
a = tf.constant(10)

sess = tf.Session()

print(sess.run(a))

10


In [7]:
import sys

sys.platform
print(sys.version_info)

sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)


In [8]:
!pip install keras

  Using cached Keras-2.0.3.tar.gz
  Using cached Theano-0.9.0.tar.gz
  Running setup.py bdist_wheel for keras: started
  Running setup.py bdist_wheel for keras: finished with status 'done'
  Stored in directory: C:\Users\06411\AppData\Local\pip\Cache\wheels\93\72\65\4924fd6b1859343291c50774e2df36919ee61c4511dc6a9890
  Running setup.py bdist_wheel for theano: started
  Running setup.py bdist_wheel for theano: finished with status 'done'
  Stored in directory: C:\Users\06411\AppData\Local\pip\Cache\wheels\d5\5b\93\433299b86e3e9b25f0f600e4e4ebf18e38eb7534ea518eba13
Successfully built keras theano


In [11]:
print(sess.run(tf.multiply(10,10)))

sess.close()


100


In [13]:
import keras

Using TensorFlow backend.


In [15]:
a = tf.reduce_mean([[1,2],[3,4]], axis=0)

sess = tf.Session()
b = sess.run(a)
print(b)

[2 3]


In [16]:
a = tf.reduce_mean([[1,2],[8,9]], axis=1)
b = sess.run(a)
print(b)


[1 8]


In [17]:
a = tf.reduce_mean([[1,2],[8,9]], axis=-1)
b = sess.run(a)
print(b)

[1 8]


In [18]:
a = tf.reduce_mean([[1,2],[8,9]], axis=-2)
b = sess.run(a)
print(b)

[4 5]


In [30]:
import numpy as np

c = np.arange(1,13).reshape(2,2,3)

d = tf.constant(c)


a = tf.reshape(d, shape=[-1,3])
print(sess.run(d))
b = sess.run(a)
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
help(tf.reshape)

Help on function reshape in module tensorflow.python.ops.gen_array_ops:

reshape(tensor, shape, name=None)
    Reshapes a tensor.
    
    Given `tensor`, this operation returns a tensor that has the same values
    as `tensor` with shape `shape`.
    
    If one component of `shape` is the special value -1, the size of that dimension
    is computed so that the total size remains constant.  In particular, a `shape`
    of `[-1]` flattens into 1-D.  At most one component of `shape` can be -1.
    
    If `shape` is 1-D or higher, then the operation returns a tensor with shape
    `shape` filled with the values of `tensor`. In this case, the number of elements
    implied by `shape` must be the same as the number of elements in `tensor`.
    
    For example:
    
    ```prettyprint
    # tensor 't' is [1, 2, 3, 4, 5, 6, 7, 8, 9]
    # tensor 't' has shape [9]
    reshape(t, [3, 3]) ==> [[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]]
    
    # 

In [31]:
help(np.reshape)

Help on function reshape in module numpy.core.fromnumeric:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the firs